name: Bug report
description: Fill out a bug report to help us improve our MarketingSoftware
body:
  - type: textarea
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen? Feel free to drop any screenshots in here.
      placeholder: I did this thing over here, and saw this error...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation
      description: How did you install Statamic?
      options:
        - Fresh statamic/statamic site via CLI
        - Starter Kit using via CLI
        - Existing Laravel app
        - Other (please explain)
    validations:
      required: true
